make:
	gcc -g src/primary_server.c src/utilities.c -o bin/primary_server.o
	gcc -g src/auth_service.c src/utilities.c -o bin/auth_service.o
	gcc -g src/client.c src/utilities.c -o bin/client.o
clean:
	rm bin/primary_server.o
	rm bin/auth_service.o
	rm bin/client.o
